// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleFastReport.API.Models
{
    public partial class DiningTable
    {
        public DiningTable()
        {
            Reservations = new HashSet<Reservation>();
        }

        public int TableId { get; set; }
        public string TableNumber { get; set; }
        public int LocationId { get; set; }
        public int Capacity { get; set; }
        public string Status { get; set; }

        public virtual Location Location { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}