// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleFastReport.API.Models
{
    public partial class Ingredient
    {
        public Ingredient()
        {
            ProductRecipes = new HashSet<ProductRecipe>();
        }

        public int IngredientId { get; set; }
        public string IngredientName { get; set; }
        public string Description { get; set; }
        public string UnitOfMeasure { get; set; }
        public decimal StockQuantity { get; set; }
        public decimal ReorderLevel { get; set; }
        public int SupplierId { get; set; }
        public decimal Cost { get; set; }

        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<ProductRecipe> ProductRecipes { get; set; }
    }
}