// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleFastReport.API.Models
{
    public partial class Location
    {
        public Location()
        {
            DiningTables = new HashSet<DiningTable>();
            Employees = new HashSet<Employee>();
            Orders = new HashSet<Order>();
            Shifts = new HashSet<Shift>();
        }

        public int LocationId { get; set; }
        public string LocationName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public DateTime OpeningDate { get; set; }
        public bool? IsActive { get; set; }

        public virtual ICollection<DiningTable> DiningTables { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Shift> Shifts { get; set; }
    }
}