// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleFastReport.API.Models
{
    public partial class Product
    {
        public Product()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }

        public int ProductId { get; set; }
        public int ProductGroupId { get; set; }
        public string ProductName { get; set; }
        public decimal ProductPrice { get; set; }
        public bool? IsActive { get; set; }
        public int CreatedByUserId { get; set; }
        public DateTime CreatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ProductGroup ProductGroup { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}