// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleFastReport.API.Models
{
    public partial class ProductCategory
    {
        public ProductCategory()
        {
            InverseParentCategory = new HashSet<ProductCategory>();
            Products = new HashSet<Product>();
        }

        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public int? ParentCategoryId { get; set; }
        public string Description { get; set; }

        public virtual ProductCategory ParentCategory { get; set; }
        public virtual ICollection<ProductCategory> InverseParentCategory { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}